### ISSUE TITLE
doesn't work on any lua version

### ISSUE THREAD

**Issue by fulcanelly** [cosmonawt/lua-telegram-bot#27] opened 2019-11-26 20:29 UTC
When I try to start this I get the error like below:

```
$ lua5.2 bot-example.lua 
lua5.2: ./lua-bot-api.lua:25: module 'ssl.https' not found:
	no field package.preload['ssl.https']
	no file '/usr/local/share/lua/5.2/ssl/https.lua'
	no file '/usr/local/share/lua/5.2/ssl/https/init.lua'
	no file '/usr/local/lib/lua/5.2/ssl/https.lua'
	no file '/usr/local/lib/lua/5.2/ssl/https/init.lua'
	no file '/usr/share/lua/5.2/ssl/https.lua'
	no file '/usr/share/lua/5.2/ssl/https/init.lua'
	no file './ssl/https.lua'
	no file '/usr/local/lib/lua/5.2/ssl/https.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/ssl/https.so'
	no file '/usr/lib/lua/5.2/ssl/https.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './ssl/https.so'
	no file '/usr/local/lib/lua/5.2/ssl.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/ssl.so'
	no file '/usr/lib/lua/5.2/ssl.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './ssl.so'
stack traceback:
	[C]: in function 'require'
	./lua-bot-api.lua:25: in main chunk
	[C]: in function 'require'
	bot-example.lua:27: in main chunk
	[C]: in ?

```

**Comment by samartinell** [comment] 2020-09-28 18:59
same problem, did you fix it? And if so, how?

**Comment by ldb** [comment] 2021-01-26 13:22
Hello, sorry for the late response. It looks like you are missing luasec to make HTTPS calls.
Please read https://github.com/ldb/lua-telegram-bot#installing.

Since this is not a bug, I will close this.

**Closed as completed by ldb** 2021-01-26 13:22 UTC
